definitions:
  model.Media:
    properties:
      content:
        type: string
      created_at:
        type: string
      media:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is API for tweets service
  title: Tweets API documentation
  version: 1.0.0
paths:
  /delete_tweet:
    delete:
      description: Delete by tweet_id
      parameters:
      - description: Tweet ID
        in: query
        name: tweet_id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            type: integer
        "404":
          description: Not Found
          schema:
            type: integer
        "405":
          description: Method Not Allowed
          schema:
            type: integer
        "500":
          description: Internal Server Error
          schema:
            type: integer
  /post_tweet:
    post:
      description: Post tweet
      parameters:
      - description: User ID
        in: body
        name: user_id
        required: true
        schema:
          type: integer
      - description: Content
        in: body
        name: content
        required: true
        schema:
          type: string
      - description: Retweet ID
        in: body
        name: retweet_id
        schema:
          type: integer
      - description: Media
        in: formData
        name: media
        type: file
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            type: integer
        "404":
          description: Not Found
          schema:
            type: integer
        "405":
          description: Method Not Allowed
          schema:
            type: integer
        "500":
          description: Internal Server Error
          schema:
            type: integer
  /retrieve_tweet:
    get:
      description: Retrieve either by tweet_id or user_id
      parameters:
      - description: User ID
        in: query
        name: user_id
        type: integer
      - description: Tweet ID
        in: query
        name: tweet_id
        type: integer
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Media'
            type: array
        "400":
          description: Bad Request
          schema:
            type: integer
        "404":
          description: Not Found
          schema:
            type: integer
        "405":
          description: Method Not Allowed
          schema:
            type: integer
        "500":
          description: Internal Server Error
          schema:
            type: integer
swagger: "2.0"
