host: localhost:8082
info:
  contact: {}
  description: This is API for follow service
  title: Follow API documentation
  version: 1.0.0
paths:
  /follow:
    post:
      description: Follow specific user
      parameters:
      - description: User ID
        in: body
        name: user_id
        required: true
        schema:
          type: integer
      - description: Following ID
        in: body
        name: following_id
        required: true
        schema:
          type: integer
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            type: integer
        "404":
          description: Not Found
          schema:
            type: integer
        "405":
          description: Method Not Allowed
          schema:
            type: integer
        "500":
          description: Internal Server Error
          schema:
            type: integer
  /following_user:
    get:
      description: Retrieve all following user
      parameters:
      - description: User ID
        in: query
        name: user_id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            items:
              type: integer
            type: array
        "400":
          description: Bad Request
          schema:
            type: integer
        "404":
          description: Not Found
          schema:
            type: integer
        "405":
          description: Method Not Allowed
          schema:
            type: integer
        "500":
          description: Internal Server Error
          schema:
            type: integer
  /unfollow:
    delete:
      description: Unfollow specific user
      parameters:
      - description: User ID
        in: query
        name: user_id
        required: true
        type: integer
      - description: Following ID
        in: query
        name: following_id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            type: integer
        "404":
          description: Not Found
          schema:
            type: integer
        "405":
          description: Method Not Allowed
          schema:
            type: integer
        "500":
          description: Internal Server Error
          schema:
            type: integer
  /user_followers:
    get:
      description: Retrieve all user followers
      parameters:
      - description: User ID
        in: query
        name: user_id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            items:
              type: integer
            type: array
        "400":
          description: Bad Request
          schema:
            type: integer
        "404":
          description: Not Found
          schema:
            type: integer
        "405":
          description: Method Not Allowed
          schema:
            type: integer
        "500":
          description: Internal Server Error
          schema:
            type: integer
swagger: "2.0"
